### PR TITLE
fix build error for typescript

### PR DESCRIPTION
**Pull request by RealRobin-com**
We had issues testing this locally before submitting the last PR. Seems we need the actioncable types in dependencies instead of dev dependencies

### CODE REVIEW

**Comment by mclintprojects** [comment]
Ahh. Does this work then?

**Comment by RealRobin-com** [comment]
I believe so. It fixed the build error I was getting.

**Comment by mclintprojects** [comment]
Alright. Thanks!

**Comment by RealRobin-com** [comment]
Thanks! that fixed it on our end.

**Pull request merged**
