### PR TITLE
Add Vue 3 compatibility 

### PR DESCRIPTION
**Pull request by x8BitRain**
Attempting to add Vue 3 support while maintaining Vue 2 support.

- [x] Works on Vue 3 - Connects and subscribes to a real websocket server without error.
- [x] Works on Vue 2 - Works the same as it did before.
- [x] Test suites are passing on Vue 3 and Vue 2.

### CODE REVIEW

**Comment by mclintprojects** [comment]
Thank you so much for working on adding Vue 3 support!

**Comment by mclintprojects** [comment]
@x8BitRain Kindly send me the code snippet for setting up ActionCableVue in Vue 3 so I can add it to the readme for other users.

**Comment by x8BitRain** [comment]
> @x8BitRain Kindly send me the code snippet for setting up ActionCableVue in Vue 3 so I can add it to the readme for other users.

You mean like this?
```

import { createApp } from "vue";
import App from "./App.vue";
import ActionCableVue from "actioncable-vue";

const websocketOptions = {
  debug: true,
  debugLevel: "error",
  connectionUrl: wss://localhost:8080,
  connectImmediately: false
};

createApp(App)
  .use(store)
  .use(router)
  .use(ActionCableVue, websocketOptions)
  .mount("#app");

```

**Comment by gglobensky** [comment]
I was wondering if there would be a way to access the $cable in the composition API. I tried passing the context and importing the destructurized cable from the library but I don't seem to understand how to do it. I can use it in Vue3 but I think it should be usable inside setup method as I need to use the old lifecycle hooks outside of setup to access this.$cable

**Comment by x8BitRain** [comment]
> I was wondering if there would be a way to access the $cable in the composition API. I tried passing the context and importing the destructurized cable from the library but I don't seem to understand how to do it. I can use it in Vue3 but I think it should be usable inside setup method as I need to use the old lifecycle hooks outside of setup to access this.$cable

You can't access `this` from setup() so you can only access this.$cable is if you export access to it from a service or store. You store this.$cable in vuex and access it from within `setup()` via store.state. Not ideal but it works. Not 100% sure on this is the _only_ way though.

**Comment by gglobensky** [comment]
I ended up using getInstance from vue like so:

const instance = getCurrentInstance();
const cable = instance.ctx.$root.$cable

Not ideal either but it works. I declare the channels like in the example and I call my setup methods in the channels hooks like so:

received(data) {
    this.receivedMessage(data)
}

granted that I returned the function receivedMessage in the setup function.

**Comment by Davidzhu001** [comment]
@gglobensky how setup works can you show a little demo

**Pull request merged**
